#!/usr/bin/env bash

echo "

set autoscale y

set datafile separator ','

set key autotitle columnhead

plot '/opt/gm.log' using 1:4 with lines, \
        '' using 1:5 with lines, \
        '' using 1:2 with lines

" | gnuplot5-qt --persist
